### **Understanding the concept of Feature Splitting(2nd part of Feature Engineering)**

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [11]:
data = pd.read_csv('/content/train.csv')

In [17]:
data.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
194,195,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44.0,0,0,PC 17610,27.7208,B4,C
434,435,0,1,"Silvey, Mr. William Baird",male,50.0,1,0,13507,55.9000,E44,S
716,717,1,1,"Endres, Miss. Caroline Louise",female,38.0,0,0,PC 17757,227.5250,C45,C
102,103,0,1,"White, Mr. Richard Frasar",male,21.0,0,1,35281,77.2875,D26,S
621,622,1,1,"Kimball, Mr. Edwin Nelson Jr",male,42.0,1,0,11753,52.5542,D19,S

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 183 entries, 1 to 889
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  183 non-null    int64
 1   Survived     183 non-null    int64
 2   Pclass       183 non-null    int64
 3   Name         183 non-null    object
 4   Sex          183 non-null    object
 5   Age          183 non-null    float64
 6   SibSp        183 non-null    int64
 7   Parch        183 non-null    int64
 8   Ticket       183 non-null    object
 9   Fare         183 non-null    float64
 10  Cabin        183 non-null    object
 11  Embarked     183 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 18.6+ KB

In [19]:
data.dropna(inplace=True)

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 183 entries, 1 to 889
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  183 non-null    int64
 1   Survived     183 non-null    int64
 2   Pclass       183 non-null    int64
 3   Name         183 non-null    object
 4   Sex          183 non-null    object
 5   Age          183 non-null    float64
 6   SibSp        183 non-null    int64
 7   Parch        183 non-null    int64
 8   Ticket       183 non-null    object
 9   Fare         183 non-null    float64
 10  Cabin        183 non-null    object
 11  Embarked     183 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 18.6+ KB

In [21]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

### **Applying Feature Splitting**

In [23]:
data['Name']

1      Cumings, Mrs. John Bradley (Florence Briggs Th...
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
6                                McCarthy, Mr. Timothy J
10                       Sandstrom, Miss. Marguerite Rut
11                              Bonnell, Miss. Elizabeth
                             ...
871     Beckwith, Mrs. Richard Leonard (Sallie Monypeny)
872                             Carlsson, Mr. Frans Olof
879        Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
887                         Graham, Miss. Margaret Edith
889                                Behr, Mr. Karl Howell
Name: Name, Length: 183, dtype: object

In [24]:
#Spitting the Name col.
data['Title'] = data['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]

In [25]:
data['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]

1       Mrs
3       Mrs
6        Mr
10     Miss
11     Miss
       ...
871     Mrs
872      Mr
879     Mrs
887    Miss
889      Mr
Name: 0, Length: 183, dtype: object

In [26]:
#naming the splitted cols.
data[['Title','Name']]

    Title                                               Name
1     Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
3     Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
6      Mr                            McCarthy, Mr. Timothy J
10   Miss                    Sandstrom, Miss. Marguerite Rut
11   Miss                           Bonnell, Miss. Elizabeth
..    ...                                                ...
871   Mrs   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)
872    Mr                           Carlsson, Mr. Frans Olof
879   Mrs      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
887  Miss                       Graham, Miss. Margaret Edith
889    Mr                              Behr, Mr. Karl Howell

[183 rows x 2 columns]

In [27]:
#Setting the conditions
data['Is_Married'] = 0
data['Is_Married'].loc[data['Title'] == 'Mrs'] = 1

<ipython-input-27-ead256fb4d9d>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Is_Married'].loc[data['Title'] == 'Mrs'] = 1

In [28]:
data['Is_Married']

1      1
3      1
6      0
10     0
11     0
      ..
871    1
872    0
879    1
887    0
889    0
Name: Is_Married, Length: 183, dtype: int64